# Generated by Django 5.2.3 on 2025-06-21 21:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('age', models.IntegerField(default='5')),
                ('study', models.CharField(default='', max_length=200)),
                ('mail', models.EmailField(default='', max_length=200)),
                ('current_job', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('website', models.CharField(default='', max_length=200)),
                ('phone', models.IntegerField(default='0')),
                ('employment_status', models.CharField(choices=[('Free of Contract', 'Free of Contract'), ('Currently under contract', 'Currently under contract')], default='', max_length=200)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 21, 21, 53, 30, 141218, tzinfo=datetime.timezone.utc))),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='', max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
