# Generated by Django 3.1 on 2020-09-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='website',
            field=models.CharField(default='www.', max_length=300),
            preserve_default=False,
        ),
    ]
