# Generated by Django 2.2.12 on 2020-08-06 20:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
