# Generated by Django 5.2.3 on 2025-07-24 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 7, 24, 15, 59, 13, 503834, tzinfo=datetime.timezone.utc)),
        ),
    ]
