# Generated by Django 3.1 on 2020-09-16 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_experience_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 12, 18, 28, 195583)),
        ),
        migrations.AddField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 12, 18, 28, 196105)),
        ),
        migrations.AddField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 12, 18, 28, 194963)),
        ),
    ]
