# Generated by Django 2.2.12 on 2020-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_auto_20200806_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
