# Generated by Django 3.1 on 2020-08-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20200829_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='chap_title',
            field=models.CharField(default='certificates', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='chap_title',
            field=models.CharField(default='contact', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='chap_title',
            field=models.CharField(default='education', max_length=200),
        ),
        migrations.AddField(
            model_name='exchange',
            name='chap_title',
            field=models.CharField(default='exchange programs', max_length=200),
        ),
        migrations.AddField(
            model_name='experience',
            name='chap_title',
            field=models.CharField(default='experience', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='chap_title',
            field=models.CharField(default='profile', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='chap_title',
            field=models.CharField(default='skills', max_length=200),
        ),
    ]
