# Generated by Django 3.1 on 2020-10-12 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0003_auto_20200916_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 20, 57, 357353)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 20, 57, 357900)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 20, 57, 356432)),
        ),
    ]
