# Generated by Django 3.1 on 2020-10-12 20:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_auto_20201012_2021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 22, 40, 229633)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 22, 40, 230208)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 12, 20, 22, 40, 228972)),
        ),
    ]
