# Generated by Django 3.1 on 2020-08-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0004_auto_20200829_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='text',
            new_name='skill_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default='5'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_job',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='freelance_status',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='study',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
