# Generated by Django 3.1 on 2020-08-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0005_auto_20200829_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default='0'),
        ),
    ]
