# Generated by Django 3.1 on 2020-09-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0007_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='freelance_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Not available', 'Not available')], default='', max_length=200),
        ),
    ]
