# Generated by Django 3.1 on 2020-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0008_auto_20200902_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.TextField(),
        ),
    ]
