# Generated by Django 3.1 on 2020-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_auto_20200902_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAbilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='forestry', max_length=200)),
            ],
        ),
    ]
