# Generated by Django 3.1.14 on 2022-02-15 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0010_auto_20220214_0815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentwork',
            options={'verbose_name': 'Recent Work', 'verbose_name_plural': 'Recent Work'},
        ),
        migrations.AddField(
            model_name='certificates',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='education',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AddField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 8, 18, 22, 427599)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 8, 18, 22, 428236)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 8, 18, 22, 426776)),
        ),
    ]
