# Generated by Django 3.1 on 2020-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0011_mainabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='education',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chap_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='freelance_status',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='chap_title',
        ),
        migrations.AddField(
            model_name='certificates',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificates',
            name='title',
            field=models.CharField(default='Hi', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(default='Hi', max_length=200),
        ),
        migrations.AddField(
            model_name='exchange',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status',
            field=models.CharField(choices=[('Free of Contract', 'Free of Contract'), ('Currently under contract', 'Currently under contract')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mainabilities',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
