# Generated by Django 3.1 on 2020-09-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0012_auto_20200903_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='from_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='to_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='year',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
