# Generated by Django 3.1.14 on 2022-02-15 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0013_auto_20220215_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificates',
            options={'verbose_name': 'Certificates', 'verbose_name_plural': 'Certificates'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Experience', 'verbose_name_plural': 'Experience'},
        ),
        migrations.AlterModelOptions(
            name='mainabilities',
            options={'verbose_name': 'MainAbilities', 'verbose_name_plural': 'MainAbilities'},
        ),
        migrations.AddField(
            model_name='certificates',
            name='cat',
            field=models.CharField(choices=[('language', 'language'), ('professional', 'professional'), ('hobby', 'hobby')], default='professional', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 22, 6, 390200, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 22, 6, 390837, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 22, 6, 389385, tzinfo=utc)),
        ),
    ]
