# Generated by Django 3.1 on 2020-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0014_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='percent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
