# Generated by Django 3.1.14 on 2022-02-15 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0014_auto_20220215_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentwork',
            name='active',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 23, 50, 355075, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 23, 50, 355809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 9, 23, 50, 354378, tzinfo=utc)),
        ),
    ]
