# Generated by Django 3.1 on 2020-09-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0015_skill_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='skill_type',
        ),
    ]
