# Generated by Django 3.1.14 on 2022-02-15 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0015_auto_20220215_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='link',
            field=models.URLField(default='aaa', max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificates',
            name='cat',
            field=models.CharField(choices=[('language', 'language'), ('technical', 'technical'), ('hobby', 'hobby')], default='technical', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 20, 40, 36, 103234, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 20, 40, 36, 103831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 15, 20, 40, 36, 102448, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('technical', 'technical'), ('general', 'general'), ('language', 'language'), ('hobby', 'hobby')], default='technical', max_length=300),
        ),
    ]
