# Generated by Django 3.1.14 on 2022-02-16 08:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0016_auto_20220215_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 8, 15, 52, 983073, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 8, 15, 52, 983707, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 8, 15, 52, 982244, tzinfo=utc)),
        ),
    ]
