# Generated by Django 3.1 on 2020-09-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0017_auto_20200904_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(choices=[('technical', 'technical'), ('professional', 'professional'), ('language', 'language')], default=' ', max_length=300),
        ),
    ]
