# Generated by Django 3.1 on 2020-09-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0019_auto_20200904_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default='True'),
        ),
    ]
