# Generated by Django 3.1.14 on 2022-02-16 15:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0020_auto_20220216_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 28, 57, 368961, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 28, 57, 369577, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 16, 15, 28, 57, 368232, tzinfo=utc)),
        ),
    ]
