# Generated by Django 3.1 on 2020-09-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0020_skill_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, upload_to='static/images')),
            ],
        ),
    ]
