# Generated by Django 3.1.14 on 2022-06-27 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0021_auto_20220216_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='CvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 13, 53, 37, 450709, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 13, 53, 37, 447155, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 13, 53, 37, 447789, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 13, 53, 37, 446422, tzinfo=utc)),
        ),
    ]
