# Generated by Django 3.1 on 2020-09-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0021_recentwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.FileField(blank=True, upload_to='images'),
        ),
    ]
