# Generated by Django 3.1.14 on 2022-06-27 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0022_auto_20220627_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 14, 30, 14, 446316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 14, 30, 14, 442661, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 14, 30, 14, 443285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 6, 27, 14, 30, 14, 441891, tzinfo=utc)),
        ),
    ]
