# Generated by Django 3.1 on 2020-09-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0022_auto_20200907_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.FileField(blank=True, upload_to='static/images'),
        ),
    ]
