# Generated by Django 3.1 on 2020-09-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0023_auto_20200907_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentwork',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
