# Generated by Django 3.2.19 on 2023-05-12 14:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0024_auto_20230512_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_en',
            field=models.CharField(default='Hi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='title_ro',
            field=models.CharField(default='Hi', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='university_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='university_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_en',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='location_ro',
            field=models.CharField(default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='position_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainabilities',
            name='name_en',
            field=models.CharField(default='forestry', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mainabilities',
            name='name_ro',
            field=models.CharField(default='forestry', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_job_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_job_ro',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status_en',
            field=models.CharField(choices=[('Free of Contract', 'Free of Contract'), ('Currently under contract', 'Currently under contract')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='employment_status_ro',
            field=models.CharField(choices=[('Free of Contract', 'Free of Contract'), ('Currently under contract', 'Currently under contract')], default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_en',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_ro',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='text_ro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='category_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='category_ro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='title_en',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='recentwork',
            name='title_ro',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cvfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 14, 18, 58, 718678, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 14, 18, 58, 714937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 14, 18, 58, 715621, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 14, 18, 58, 714166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recentwork',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
