# Generated by Django 3.2.19 on 2023-05-12 19:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0025_auto_20230512_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvfile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 19, 9, 29, 626657, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='education',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 19, 9, 29, 623037, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='experience',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 19, 9, 29, 623696, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 12, 19, 9, 29, 622273, tzinfo=utc)),
        ),
    ]
