# Generated by Django 3.1 on 2020-09-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0026_auto_20200907_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
