# Generated by Django 3.1 on 2020-09-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0027_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='text',
            field=models.TextField(),
        ),
    ]
